Editted Search Bar with more entries
Mmendero/SPS-Team-Project-Name-TBD- pull request #7
Opened 2020-07-19 01:41 UTC by Mmendero

++ Added two inputs for searching content ("Type" and "Submit")
-- Changed Intro text to add website goal/target
-- Updated contacts page with placeholder information
-- Adjusted navigation bar hyperlinks

![site page](https://user-images.githubusercontent.com/39359693/87865134-5e462780-c93f-11ea-81e5-04114d50fded.png)

2020-07-19 15:49 UTC, Mmendero commented
With my latest commit, I:

- Deleted/renamed the files **input.html**, **output.html**, and **test.html** as I integrated them with the website and have allowed for navigation to these features within the site. (input.html can be accessed using the **"Add Listing"** button on navigation bar)

![image](https://user-images.githubusercontent.com/39359693/87878906-3e514b00-c9b5-11ea-9f28-d78ce2c1c312.png)


- Editted the **script.js** file's **search()** function to read the altered elements within the front page to make the searching feature on the front page functional

**New:**
![image](https://user-images.githubusercontent.com/39359693/87878956-a142e200-c9b5-11ea-9209-4e29ecfb48e1.png)
**After Searching:**
![image](https://user-images.githubusercontent.com/39359693/87878994-d94a2500-c9b5-11ea-8603-9a6ef40eb34f.png)

2020-07-19 17:39 UTC, matthewlam99 commented on Site_Files/src/main/webapp/add.html
> +            <textarea name="name-imput">name</textarea>
NITPICK: input is spelt wrong

2020-07-19 17:43 UTC, matthewtlam approved these changes
Everything looks good. It was a great idea to separate the input form as a separate page. I was also thinking about making the "type" category as a selector with options but you beat me to it. I'm not looking forward to all the merge conflicts I'm gonna have though later, but great job!

2020-07-20 23:34 UTC, ben188ben188 commented
read

2020-07-20 23:46 UTC, ben188ben188 requested changes
Looks good

2020-07-20 23:51 UTC, ben188ben188 approved these changes

2020-07-21 18:53 UTC, perrycate approved these changes

2020-07-21 18:53 UTC, perrycate commented on Site_Files/src/main/webapp/index.html
> +        <p id="intro">Welcome to [REDACTED]! Our goal is to expand your reach and radar when it comes to furthering your career in CS. Here, you'll be able to look for a wide variety of different res
Lol redacted

2020-07-21 18:56 UTC, perrycate commented
Btw thanks for including screensshots in your PR, was super helpful!

2020-07-22 23:15 UTC, merged